version: "3"

services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "7000:5432"
  app:
    image: asmaa/practicum
